name: fincheck
services:
  postgres:
    image: postgres:latest
    container_name: fincheck
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
